org.gradle.jvmargs=-Xmx384m -Xss384k -XX:ActiveProcessorCount=2 -XX:CICompilerCount=2 -XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m
org.gradle.parallel=false
org.gradle.configuration-cache=false

minecraft_version=1.21.9
loader_version=0.19.3
loom_version=1.17.17
fabric_api_version=0.134.1+1.21.9
fabric_api_min_version=0.134.1

mod_version=1.5.1
maven_group=com.liy
archive_base_name=level10-enchantments
