org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=false

minecraft_version=1.21.1
loader_version=0.19.3
loom_version=1.17.17
fabric_api_version=0.116.14+1.21.1
fabric_api_min_version=0.116.14

mod_version=1.5.1
maven_group=com.liy
archive_base_name=level10-enchantments
