org.gradle.jvmargs=-Xmx512m -Xss512k -XX:CICompilerCount=2
org.gradle.parallel=true
org.gradle.configuration-cache=false

minecraft_version=1.21.3
loader_version=0.19.3
loom_version=1.17.17
fabric_api_version=0.114.1+1.21.3
fabric_api_min_version=0.114.1

mod_version=1.5.1
maven_group=com.liy
archive_base_name=level10-enchantments
